// Generated by assets/tools/optimize-images.py. Do not edit by hand.
export type ImageEntry = { src: string; srcSet?: string; width: number; height: number };

export const IMAGES: Record<string, ImageEntry> = {
  "/images/hero6.jpg": {
    "src": "/images/opt/hero6-1200.webp",
    "srcSet": "/images/opt/hero6-480.webp 480w, /images/opt/hero6-800.webp 800w, /images/opt/hero6-1200.webp 1200w, /images/opt/hero6-1600.webp 1600w, /images/opt/hero6-2000.webp 2000w, /images/opt/hero6-2400.webp 2400w",
    "width": 2400,
    "height": 1600
  },
  "/images/about-hero.jpg": {
    "src": "/images/opt/about-hero-1200.webp",
    "srcSet": "/images/opt/about-hero-480.webp 480w, /images/opt/about-hero-800.webp 800w, /images/opt/about-hero-1200.webp 1200w, /images/opt/about-hero-1600.webp 1600w, /images/opt/about-hero-2000.webp 2000w, /images/opt/about-hero-2400.webp 2400w",
    "width": 2400,
    "height": 1600
  },
  "/images/careers-hero.jpg": {
    "src": "/images/opt/careers-hero-1200.webp",
    "srcSet": "/images/opt/careers-hero-480.webp 480w, /images/opt/careers-hero-800.webp 800w, /images/opt/careers-hero-1200.webp 1200w, /images/opt/careers-hero-1600.webp 1600w, /images/opt/careers-hero-2000.webp 2000w, /images/opt/careers-hero-2390.webp 2390w",
    "width": 2390,
    "height": 1454
  },
  "/images/about-security.jpg": {
    "src": "/images/opt/about-security-1200.webp",
    "srcSet": "/images/opt/about-security-480.webp 480w, /images/opt/about-security-800.webp 800w, /images/opt/about-security-1200.webp 1200w, /images/opt/about-security-1408.webp 1408w",
    "width": 1408,
    "height": 736
  },
  "/images/about-banner.jpg": {
    "src": "/images/opt/about-banner-1200.webp",
    "srcSet": "/images/opt/about-banner-480.webp 480w, /images/opt/about-banner-800.webp 800w, /images/opt/about-banner-1200.webp 1200w, /images/opt/about-banner-1600.webp 1600w, /images/opt/about-banner-2000.webp 2000w",
    "width": 2000,
    "height": 1391
  },
  "/images/services-hero/denver-sunset.webp": {
    "src": "/images/opt/services-hero-denver-sunset-1200.webp",
    "srcSet": "/images/opt/services-hero-denver-sunset-480.webp 480w, /images/opt/services-hero-denver-sunset-800.webp 800w, /images/opt/services-hero-denver-sunset-1200.webp 1200w, /images/opt/services-hero-denver-sunset-1600.webp 1600w, /images/opt/services-hero-denver-sunset-2000.webp 2000w, /images/opt/services-hero-denver-sunset-2400.webp 2400w",
    "width": 2400,
    "height": 1380
  },
  "/images/services-hero/nb-s1-towers.webp": {
    "src": "/images/opt/services-hero-nb-s1-towers-1200.webp",
    "srcSet": "/images/opt/services-hero-nb-s1-towers-480.webp 480w, /images/opt/services-hero-nb-s1-towers-800.webp 800w, /images/opt/services-hero-nb-s1-towers-1200.webp 1200w, /images/opt/services-hero-nb-s1-towers-1600.webp 1600w, /images/opt/services-hero-nb-s1-towers-2000.webp 2000w, /images/opt/services-hero-nb-s1-towers-2400.webp 2400w, /images/opt/services-hero-nb-s1-towers-2752.webp 2752w",
    "width": 2752,
    "height": 1536
  },
  "/images/capability-hero/cs-fins.webp": {
    "src": "/images/opt/capability-hero-cs-fins-1200.webp",
    "srcSet": "/images/opt/capability-hero-cs-fins-480.webp 480w, /images/opt/capability-hero-cs-fins-800.webp 800w, /images/opt/capability-hero-cs-fins-1200.webp 1200w, /images/opt/capability-hero-cs-fins-1600.webp 1600w, /images/opt/capability-hero-cs-fins-2000.webp 2000w, /images/opt/capability-hero-cs-fins-2400.webp 2400w, /images/opt/capability-hero-cs-fins-2752.webp 2752w",
    "width": 2752,
    "height": 1536
  },
  "/images/careers-philosophy.jpg": {
    "src": "/images/opt/careers-philosophy-1184.webp",
    "srcSet": "/images/opt/careers-philosophy-480.webp 480w, /images/opt/careers-philosophy-800.webp 800w, /images/opt/careers-philosophy-1184.webp 1184w",
    "width": 1184,
    "height": 880
  },
  "/images/careers-team.jpg": {
    "src": "/images/opt/careers-team-1184.webp",
    "srcSet": "/images/opt/careers-team-480.webp 480w, /images/opt/careers-team-800.webp 800w, /images/opt/careers-team-1184.webp 1184w",
    "width": 1184,
    "height": 880
  },
  "/images/mission-vehicle.jpg": {
    "src": "/images/opt/mission-vehicle-750.webp",
    "srcSet": "/images/opt/mission-vehicle-480.webp 480w, /images/opt/mission-vehicle-750.webp 750w",
    "width": 750,
    "height": 842
  },
  "/images/officer-portrait.jpg": {
    "src": "/images/opt/officer-portrait-992.webp",
    "srcSet": "/images/opt/officer-portrait-480.webp 480w, /images/opt/officer-portrait-800.webp 800w, /images/opt/officer-portrait-992.webp 992w",
    "width": 992,
    "height": 1040
  },
  "/images/backbone-officer.jpg": {
    "src": "/images/opt/backbone-officer-733.webp",
    "srcSet": "/images/opt/backbone-officer-480.webp 480w, /images/opt/backbone-officer-733.webp 733w",
    "width": 733,
    "height": 900
  },
  "/images/matrix-government.jpg": {
    "src": "/images/opt/matrix-government-640.webp",
    "srcSet": "/images/opt/matrix-government-480.webp 480w, /images/opt/matrix-government-640.webp 640w",
    "width": 640,
    "height": 427
  },
  "/images/matrix-government.webp": {
    "src": "/images/opt/matrix-government-862.webp",
    "srcSet": "/images/opt/matrix-government-480.webp 480w, /images/opt/matrix-government-800.webp 800w, /images/opt/matrix-government-862.webp 862w",
    "width": 862,
    "height": 862
  },
  "/images/matrix-specialized.jpg": {
    "src": "/images/opt/matrix-specialized-640.webp",
    "srcSet": "/images/opt/matrix-specialized-480.webp 480w, /images/opt/matrix-specialized-640.webp 640w",
    "width": 640,
    "height": 384
  },
  "/images/matrix-industrial.jpg": {
    "src": "/images/opt/matrix-industrial-640.webp",
    "srcSet": "/images/opt/matrix-industrial-480.webp 480w, /images/opt/matrix-industrial-640.webp 640w",
    "width": 640,
    "height": 360
  },
  "/images/matrix-airport-denver.jpg": {
    "src": "/images/opt/matrix-airport-denver-1200.webp",
    "srcSet": "/images/opt/matrix-airport-denver-480.webp 480w, /images/opt/matrix-airport-denver-800.webp 800w, /images/opt/matrix-airport-denver-1200.webp 1200w, /images/opt/matrix-airport-denver-1600.webp 1600w",
    "width": 1600,
    "height": 1143
  },
  "/images/matrix-commercial.jpg": {
    "src": "/images/opt/matrix-commercial-1000.webp",
    "srcSet": "/images/opt/matrix-commercial-480.webp 480w, /images/opt/matrix-commercial-800.webp 800w, /images/opt/matrix-commercial-1000.webp 1000w",
    "width": 1000,
    "height": 667
  },
  "/images/matrix-community.jpg": {
    "src": "/images/opt/matrix-community-640.webp",
    "srcSet": "/images/opt/matrix-community-480.webp 480w, /images/opt/matrix-community-640.webp 640w",
    "width": 640,
    "height": 427
  },
  "/images/capability-page1.webp": {
    "src": "/images/opt/capability-page1-1000.webp",
    "srcSet": "/images/opt/capability-page1-480.webp 480w, /images/opt/capability-page1-800.webp 800w, /images/opt/capability-page1-1000.webp 1000w",
    "width": 1000,
    "height": 1295
  },
  "/images/market/data-centers.webp": {
    "src": "/images/opt/market-data-centers-1200.webp",
    "srcSet": "/images/opt/market-data-centers-480.webp 480w, /images/opt/market-data-centers-800.webp 800w, /images/opt/market-data-centers-1200.webp 1200w, /images/opt/market-data-centers-1600.webp 1600w, /images/opt/market-data-centers-2000.webp 2000w, /images/opt/market-data-centers-2048.webp 2048w",
    "width": 2048,
    "height": 1144
  },
  "/images/market/government-military.webp": {
    "src": "/images/opt/market-government-military-1200.webp",
    "srcSet": "/images/opt/market-government-military-480.webp 480w, /images/opt/market-government-military-800.webp 800w, /images/opt/market-government-military-1200.webp 1200w, /images/opt/market-government-military-1600.webp 1600w, /images/opt/market-government-military-2000.webp 2000w, /images/opt/market-government-military-2048.webp 2048w",
    "width": 2048,
    "height": 1144
  },
  "/images/market/construction-industrial.webp": {
    "src": "/images/opt/market-construction-industrial-1200.webp",
    "srcSet": "/images/opt/market-construction-industrial-480.webp 480w, /images/opt/market-construction-industrial-800.webp 800w, /images/opt/market-construction-industrial-1200.webp 1200w, /images/opt/market-construction-industrial-1600.webp 1600w, /images/opt/market-construction-industrial-2000.webp 2000w, /images/opt/market-construction-industrial-2048.webp 2048w",
    "width": 2048,
    "height": 1144
  },
  "/images/market/commercial-property.webp": {
    "src": "/images/opt/market-commercial-property-1200.webp",
    "srcSet": "/images/opt/market-commercial-property-480.webp 480w, /images/opt/market-commercial-property-800.webp 800w, /images/opt/market-commercial-property-1200.webp 1200w, /images/opt/market-commercial-property-1600.webp 1600w, /images/opt/market-commercial-property-2000.webp 2000w, /images/opt/market-commercial-property-2048.webp 2048w",
    "width": 2048,
    "height": 1144
  },
  "/images/cert-gsa-footer.png": {
    "src": "/images/opt/cert-gsa-footer.webp",
    "width": 534,
    "height": 128
  },
  "/images/cert-sba-footer.png": {
    "src": "/images/opt/cert-sba-footer.webp",
    "width": 466,
    "height": 128
  },
  "/images/cert-women-owned.png": {
    "src": "/images/opt/cert-women-owned.webp",
    "width": 290,
    "height": 128
  },
  "/images/cert-wbenc.png": {
    "src": "/images/opt/cert-wbenc.webp",
    "width": 226,
    "height": 128
  },
  "/images/gsa-contract-holder.png": {
    "src": "/images/opt/gsa-contract-holder.webp",
    "width": 534,
    "height": 128
  },
  "/images/cert-denver-edo.webp": {
    "src": "/images/opt/cert-denver-edo.webp",
    "width": 492,
    "height": 128
  },
  "/images/cert-sba-wosb.webp": {
    "src": "/images/opt/cert-sba-wosb.webp",
    "width": 353,
    "height": 128
  },
  "/images/cert-co-diverse.webp": {
    "src": "/images/opt/cert-co-diverse.webp",
    "width": 371,
    "height": 128
  },
  "/images/cert-co-small.webp": {
    "src": "/images/opt/cert-co-small.webp",
    "width": 371,
    "height": 128
  }
};
